/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: tonyflanagan (https://sketchfab.com/tonyflanagan)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/undercover-cop-animated-5228453f76474727af2332da0d71e138
title: Undercover Cop - Animated
*/

import React, { useRef } from "react"
import { useGLTF, useAnimations } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"

export default function CopModel({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF("/scene.gltf")
  const { actions } = useAnimations(animations, group)
  console.log(actions)

  useFrame()

  return (
    <group ref={group} {...props} dispose={null} position={[0, -1, 0]}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={1.77}>
          <group>
            <group rotation={[Math.PI / 2, 0, 0]}>
              <group rotation={[Math.PI / 2, 0, 0]}>
                <group>
                  <primitive object={nodes.GLTF_created_0_rootJoint} />

                  <skinnedMesh
                    geometry={nodes.Object_7.geometry}
                    material={materials.body}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_9.geometry}
                    material={materials.bottom}
                    skeleton={nodes.Object_9.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_11.geometry}
                    material={nodes.Object_11.material}
                    skeleton={nodes.Object_11.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_13.geometry}
                    material={nodes.Object_13.material}
                    skeleton={nodes.Object_13.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_15.geometry}
                    material={materials.glasses_Bake1}
                    skeleton={nodes.Object_15.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_17.geometry}
                    material={materials.hair}
                    skeleton={nodes.Object_17.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_19.geometry}
                    material={materials.head}
                    skeleton={nodes.Object_19.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_21.geometry}
                    material={materials.shoes}
                    skeleton={nodes.Object_21.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_23.geometry}
                    material={materials.teeth}
                    skeleton={nodes.Object_23.skeleton}
                  />
                  <skinnedMesh
                    geometry={nodes.Object_25.geometry}
                    material={materials.material}
                    skeleton={nodes.Object_25.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/scene.gltf")
